apiVersion: batch/v1
kind: Job
metadata:
  name: hello-k8s-job
spec:
  template:
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never
  backoffLimit: 4 # Number of retries in case of failure
